import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";



// shared UI components
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

// global context for shared global vars
import { GlobalContext, GlobalProvider } from "./context/GlobalContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// this get loaded once and stays, not useful for SEO
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap all of the variables with GlobalProvider so that all components have access to these variables */}
        <GlobalProvider>
          <Navbar />
          {/* individual pages */}
          {children}
          <Footer />
        </GlobalProvider>
      </body>
    </html>
  );
}
